## ARRAY    (Arreglos)   -   Library : Numpy

### Vectors and Matrix




In [17]:
## Intro
## Lista

Lista1=[1,2,3,4]
print(Lista1)

[1, 2, 3, 4]


### Vectors

In [2]:
import numpy as np

v1=np.array([2, 3, 5])
print(v1)

[2 3 5]


In [18]:
v1=np.array([2,5,3,4])
print(v1)

[2 5 3 4]


In [3]:
v2=np.array([ -2, 3, 5, 6 ])
print (v2)

[-2  3  5  6]


**OPERATIONS with Vectors**

In [12]:
## Sean los vectores
v1=np.array([1, 3, 5])
v2=np.array([2, -1, 4])

#Suma
print("Sum")
print (v3 + v4)



Sum
[3 2 9]


In [14]:
## Sean los vectores
v=np.array([1, 3, 5])

# Multiplicacion por un escalar k=5
print("Multiplied for scalar 5 x V:")
print(3*v1)

Multiplied for scalar 5 x V:
[ 3  9 15]


## Matrix in Python

$$ M{m}x{n} $$

## Multiplicacion de Matrices : method 1
Define matrix, whith List

Matriz cuadrada A(nxn)

In [1]:
m1=[[2,3,4],[3,4,2],[2,5,6]]

m2=[[1,5,4],[2,6,7],[7,8,3]]

m=[[0,0,0],[0,0,0],[0,0,0]]

for x in range(0,3):
    for y in range(0,3):
        for z in range(0,3):
            m[x][y]+=m1[x][z]*m2[z][y]
print (m)

[[36, 60, 41], [25, 55, 46], [54, 88, 61]]


In [2]:
for i in range(5):
    print(i)

0
1
2
3
4


## Multiplicacion de Matrices : method 2
Whith  Library numpy

## Se usara libreria numpy, para usar pi

  Multiplicar 2 Matrices
 m1(3x3) y m2(3x3)

In [4]:
import numpy as np

m1=[[2,3,4],[3,4,2],[2,5,6]]

m2=[[1,5,4],[2,6,7],[7,8,3]]

m=np.dot(m1,m2)

print(m)

[[36 60 41]
 [25 55 46]
 [54 88 61]]


In [5]:
A=[[1,-1],[3,1]]
B=[[4,1],[-2,2]]

A=np.matrix(A)
B=np.matrix(B)

A*B

matrix([[ 6, -1],
        [10,  5]])

Multiplicacion A(mxn)*B(nxp) = M(mxp)

In [6]:
m1=[[1,2,3],[2,4,6],[4,7,5]]
y=[[1],[1],[1]]

n=np.dot(m1,y)
print (n)


[[ 6]
 [12]
 [16]]


In [22]:
## Matriz M2x3     (2 filas 3 columnas)
M1=np.array([[1, 2, -5],[2, -3, 9]])
print(M1)

[[ 1  2 -5]
 [ 2 -3  9]]


In [21]:
# Matriz M3x3
M2=np.array([[3, 6, -5],[1, -3, 5], [1, 3, -2 ]])
print(M2)

[[ 3  6 -5]
 [ 1 -3  5]
 [ 1  3 -2]]


In [23]:
# Matriz M1x4
M3=np.array([[1,3,5,7]])
print(M3)

[[1 3 5 7]]


In [25]:
# Matriz M3x4
M4=np.array([
    [1,2,3,4],
    [3,-2,6,3],
    [6,2,9,1]
])
print(M4)

[[ 1  2  3  4]
 [ 3 -2  6  3]
 [ 6  2  9  1]]


In [26]:
M5=np.array([
    [1,6,3],
    [3,-2,6],
    [5,0,1]
])
print(M5)

[[ 1  6  3]
 [ 3 -2  6]
 [ 5  0  1]]


In [27]:
M4.shape

(3, 4)

In [28]:
M5.shape

(3, 3)

In [29]:
M4.ndim

2

In [30]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

### TRANSPUESTA

In [38]:
# Transpuesta
v=np.array([[1,2,3]])
print(v)
print("Transpuesta")
v.T

[[1 2 3]]
Transpuesta


array([[1],
       [2],
       [3]])

In [37]:
# Transpuesta
v1=np.array([[1,2,3],[1,0,5]])
print("V1\n",v1,"\n")

print("Transpuesta")
T1=v1.T
print(T1)

V1
 [[1 2 3]
 [1 0 5]] 

Transpuesta
[[1 1]
 [2 0]
 [3 5]]


## Product of Matrix

In [45]:
# Matriz N1x2
N=np.array([[1,3]])
print(N)

print("\n")

# Matriz M2x3
M=np.array([[1,3, 6],[2,5,1]])
print(M)
P=np.dot(N,M)

print("\n")
print("The product of matrix is:")
print(P)

[[1 3]]


[[1 3 6]
 [2 5 1]]


The product of matrix is:
[[ 7 18  9]]


In [48]:
# Matriz  V1(1x5)
v1=np.array([[1,2,3,4,5]])
print("v1=",v1)

print("\n")

# Matriz  V2(5x1)
v2=np.array([[3,0,1,4,2]]).T
print("v2=\n", v2)

print("\n")

#Matriz  C(1x1)
print("The product of matrix is:")
c=np.dot(v1,v2)

print("\n")

print("P=",c)

v1= [[1 2 3 4 5]]


v2=
 [[3]
 [0]
 [1]
 [4]
 [2]]


The product of matrix is:


P= [[32]]


In [49]:
v1_1=np.array([[1,2,3,4,5]])
print(v1_1)
v2_1=np.array([[2,3,4,5,6]]).T
print(v2_1)

print("The product of matrix is:")
c1=np.dot(v1_1,v2_1)

print(c1)

[[1 2 3 4 5]]
[[2]
 [3]
 [4]
 [5]
 [6]]
The product of matrix is:
[[70]]
